### ISSUE TITLE
The correlation matrix is calculated by what?

### ISSUE THREAD

**Issue by kanghui-learning** [Matt-OP/fasteda#1]
Hi, I want to know how you calculate the correlation matrix, do you call some other library? Tks！

**Comment by Matt-OP** [comment]
Hi learner-NKH,

The correlation matrix is calculated with Pandas DataFrame `.corr()` method. The type of correlation used is the default value for the `.corr()` method which is Pearson correlation. Here is the line of the code that creates the correlation matrix:

`sns.heatmap(df.corr(), annot = True, cmap = "Spectral", linewidths = 2, linecolor = "#000000", fmt='.3f')`

**Comment by kanghui-learning** [comment]
Thanks for your prompt response. That's helpful!
